### ISSUE TITLE
[Use case] Tidyverse functions for sftrack/sftraj objects

### ISSUE THREAD

**Issue by henningte** [mablab/sftrack#13]
**Use case:**
Application of tidyverse functions, in analogy to the corresponding methods for `sf` objects, on `sftrack`/`sftraj` objects. A particular use case may be to summarise fixes (points/steps) and related data according to some grouping variable. 

**Requirements:**
Starting from a `sftrack`/`sftraj` object, it may be best to provide a new method based on the corresponding sf tidyverse methods (e.g. `summarise.sf()`) that could handle the spatial part. 

In addition, such a method probably should handle `multi_burst` objects in a special way. I don't have an overview over all tidyverse functions, so I focus on the `summarise()` topic. 

`summarise()` may have the following effects on the `burst` variable:  
1. In the simplest case, values are only summarised *within* `burst` levels. In this case, the `ind_burst`  for the summarised row could be identical to one of the (identical) input `ind_burst` objects.  
2. In a more complicated case, values are summarised *across*  `burst` levels.  It would thus be required to provide consistent methods to redefine `ind_burst` objects (e.g. by (1) assigning a new id to summarised points and (2) using the new grouping variables as new elements of the new `ind_burst` object). It may also be useful to throw a warning in this case.   

I've spotted some potential issues in the current code that may cause problems (I would not call myself too experienced, so I'm not sure if my observations are correct. I was also unsure if this is the right place to post it, but I came across it while trying to apply tidyverse fuctions on `sftrack objects`):  
1. The class of `sftrack` objects is currently `c("sftrack", "data.frame", "sf")`, but for correct method dispatch with the sf package it should be `c("sftrack", "sf", "data.frame")`.  
2. The class of `multi_burst` objects is currently `c("multi_burst")`, but for congruence with tidyverse functions, I think one should change it to `c("multi_burst", "list")`.

**Input:**
1. `sftrack`/`sftraj` object.
2. `...` arguments passed to the tidyverse functions.
3. Possibly additional arguments on how to handle the `burst` variable.

**Output:**
`sftrack`/`sftraj` object.

**Additional information:**
sf tidyverse methods: https://r-spatial.github.io/sf/reference/tidyverse.html

**Comment by birderboone** [comment]
Thanks for the suggestions. We expect sftrack to integrate with tidyverse at release, but at present have been working through standard methods first. So I have infact skated past some issues as you've pointed out. Tidyverse integration may require some reworking of the current structure to make it fit and these are good points to keep in mind. I'll have to come back to this thread as I start tackling tidyverse.

Thanks!

**Comment by basille** [comment]
Closing this issue now that `sftrack` is developed and on CRAN.
