### ISSUE TITLE
Names of sftrack variables (the big 4)

### ISSUE THREAD

**Issue by birderboone** [mablab/sftrack#18]
We consider that tracking data can consist of x,y,z,t,id,error dimensions. For the current state of an `sftrack` object we require:
Coordinates (x,y,z) - Created as an sfc geometry column
A timestamp (t in posix/integer)
A grouping column (id) - currently called 'burs't
And optional error.

Each of these objects as an associated attribute at the `sftrack` level that describes the associated column name of the variable in the data.frame. Also if the data is supplied as a vector then a default column name is appended to the output data.frame. What should the names of these attributes and their created columns be?

- sf geometrys are created via `st_as_sf` and therefore are called 'Geometry' by default. The associated attribute is also `sf_column` which is created by `sf` as well. Both of these should likely not change.

- time column is named `reloc_time` (standing for relocation time) and the attribute is currently called 'time`, which is pretty generic, I agree with previous comments that the argument should likely be called 'timestamp'. The column name might need to be something less generic as timestamp is a common column name in tracking data.   

- grouping column is currently called `burst` as well as the attribute, however, this term does not seem to be universally known and not completely describe the purpose of the column. Theres been discussion that the attribute should be called a `grouping` or `group`, the column name would have to be something less common.

- error is called `error` as an attribute and `sftrack_error` currently. Both are up for debate.

**Comment by birderboone** [comment]
My personal thoughts. I think having a prefix the way `sf` does might be the easiest thing to circumvent the column name issues, something like `sft_` or `track_`, that way we have little chance that column already existed in the users data.frame.

**Comment by basille** [comment]
My take on it:
* I'm in favor of a prefix, but that also opens more questions. I like `sft_`, unless we can get both `track_` and `traj_` separately for each type of object (after all, geometries and timestamps are different for locations and steps). However, this will only apply to timestamp, grouping and error, right? Not the geometry itself (I agree, better to leave it to `sf` itself), which might actually be confusing. Maybe we could also have a `sft_geometry` attribute, which simply retrieves (and sets) the `sf_column` one?
* I think we should leave the option to use whatever name the user wants (with arguments like `timestamp_name`, `grouping_name`, etc. in the function), as long as we provide sane defaults.
* If the column names are already taken, the function should fail, unless `overwrite = TRUE`, in which case it should proceed, overwrite existing columns, and still throw a warning.
* My preferences for default pairs of attribute names/column names are (or a variant with `track_`/`traj_` as described above): 
"geometry": `sft_geometry` = `sf_column`
"timestamp": `sft_timestamp`
"grouping": `sft_grouping`
"error": `sft_error`

**Comment by basille** [comment]
Closing this issue now that `sftrack` is developed and on CRAN.
