### ISSUE TITLE
Names of the row level and column level grouping class.

### ISSUE THREAD

**Issue by birderboone** [mablab/sftrack#19]
Similar to the `sfc` and `sfg` classes in sf, our grouping class ('burst') has two main classes:
- The single row level, one list object that contains all the named grouping levels. Currently called a 'ind_burst' (standing for individual burst).    
- The column level, a column of a collection of the single row level objects. Currently called a 'multi_burst'.  

Given we retain this structure what should the classes be named that is both short and understandable to their purposes. It has been suggested to use a similar naming structure as the sf geometry column and use something akin to 'burstc' and 'burstg' for each level.

This is somewhat dependent on if we change from calling it a `burst` to a `group`, but the idea remains the same.

**Comment by basille** [comment]
See my comments on #18 about specific names. In addition, I would argue for "grouping" (column) and "grouping_row" or "single_grouping" as they seem mostly unambiguous. I would avoid "ind" vs. "multi" as they are instead ambigous: "ind" could refere to the actual individual that is tracked, and "multi" seems to imply several grouping levels, which is not necessarily the case, nor its intended meaning.
