### ISSUE TITLE
The structure and function of the error column

### ISSUE THREAD

**Issue by birderboone** [mablab/sftrack#20]
This column/attribute has largely been in a placeholder that we wanted to make sure existed, but wasnt sure what it would look like.

So lets start the discussion, what does an error column need to do? What structure should it look like? What should be required for it? 

Is this a post processing column where you create the error using various other packages and its simply a column that stores the error. Or is it a column that you create with `as_sftrack` and contains all the error variables you can use later (i.e hdop, vdop, etc).

**Comment by basille** [comment]
Closing this issue now that `sftrack` is developed and on CRAN.
