### ISSUE TITLE
What common step metrics should sftrack calculate.

### ISSUE THREAD

**Issue by birderboone** [mablab/sftrack#24]
The `step_metrics()` attempts to calculate common metrics between successive steps in an `sftrack`/`sftraj`. Currently those are:

- dx
- dy
- distance
- speed 
- absolute angle 

What other standardized metrics should be calculated?

**Comment by birderboone** [comment]
From a conversation from @rociojoo . Relative Angle should be added as well.

**Comment by pratikunterwegs** [comment]
Hi, just jumping in here, I wonder whether `dt` (difftime) is something that's already present and if you might want to add that?
Might help users separate data based on large time intervals, which could indicate missing data in between.

**Comment by rociojoo** [comment]
Yes, dt is already there :)

**Comment by basille** [comment]
* Also to be computed, turn angles. Also known as "relative angles" (`adehabitatLT`) or "turning angles" (Turchin for instance). (I personally advocate for "turn angles"). Assumes ordering of steps. If an `sftraj` object is provided, there needs to be a check that the current step's start point is the same as the previous step's end point — but I would suggest not to reorder (can throw a warning if steps are not in order).
* Each metric should have their own vectorized function, such as `step_dx`, `step_turn_angle`, etc. as to only compute one metric on the file as a vector.
* As `step_metrcis` returns a `data.frame`, it would be good to be able to select which metrics to return — and possibly leave the possibility for the user to rename those in the arguments.

**Comment by basille** [comment]
Closing this issue now that `sftrack` is developed and on CRAN.
