### ISSUE TITLE
README example doesn't run

### ISSUE THREAD

**Issue by edzer** [mablab/sftrack#31]
I tried the README example with both github master and dev versions, but get:
```
> my_sftrack <- as_sftrack(
+   data = raccoon,
+   coords = c("longitude","latitude"),
+   time = "timestamp",
+   burst = "animal_id",
+   crs = "+init=epsg:4326")
Error in check_names_exist(data, group) : id not found in data frame
```

**Comment by basille** [comment]
Ha, my bad! `burst` has been changed to `group` to more clearly reflect what it actually is… and I forgot to update the documentation. The example works fine with:

```
my_sftrack <- as_sftrack(
  data = raccoon,
  coords = c("longitude","latitude"),
  time = "timestamp",
  group = "animal_id",
  crs = "+init=epsg:4326")
head(my_sftrack)
```

Thanks for reporting it!

**Comment by basille** [comment]
Closing this issue now, I just updated the docs online. That was somewhat of a rough start. :)
Please refresh your cache if necessary.
