### ISSUE TITLE
Travis problem installing gsl on linux

### ISSUE THREAD

**Issue by birderboone** [mablab/sftrack#34]
On dev branch travis is now failing on installing gsl, which is probably from adding amt and tracker to suggests. Internet suggest we may need to add some imports so travis can pass. But I havent looked into it thoroughly. This is likely a travis only issue and not a cran check issue as cran checks didnt seem to have this problem for me

**Comment by pratikunterwegs** [comment]
Hi, sorry to jump in, I get new issue alerts.
I guess you could solve it by adding `libgsl-dev` under `apt` `packages`, should help the `gsl` package install.
Hope it helps, apologies otherwise!

**Comment by basille** [comment]
Thanks @pratikunterwegs for jumping in! I have added `libgsl-dev` as you suggested… and that seemed to do the trick. Thanks a bunch for stopping by and helping us here!

For the record: https://travis-ci.org/github/mablab/sftrack/builds/737126933

**Comment by pratikunterwegs** [comment]
Happy to help :)
