### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rociojoo** [mablab/sftrack#35]
In Lucia's computer (Windows):

with remotes::install_github("mablab/sftrack")

error:
c2f78e3/Figures/conceptual-model-full.png: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Failed to install 'sftrack' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)

**Comment by basille** [comment]
I would need more information to confirm, but my best guess is that it comes from Windows using a [non-standard version of tar](https://github.com/juliasilge/tidytext/issues/138) (here through `tar.exe`). Please try the following first in R:

```r
Sys.setenv("TAR" = "internal")
remotes::install_github("mablab/sftrack")
```

If this succeeds, then simply add the first line to your `.Rprofile` to solve the problem forever.

As an aside, better to install the package with the vignettes! Right now, there is also some virtue using the `dev` branch, which brings a couple of neat new features:

```r
remotes::install_github("mablab/sftrack", ref = "dev", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)
```
