### ISSUE TITLE
[Use case] Create a `sftraj` object

### ISSUE THREAD

**Issue by jmsigner** [mablab/sftrack#4]
**Use case:**
I would find it very useful to have a method to create a `sftraj` from different other objects (e.g., `data.frame` and `tibble`, from `SpatialPoints*`` and corresponding `sf` objects. 

**Requirements:**
Coordinates, time stamps, CRS. 

**Input:**
A `data.frame`, `tibble`, `SpatialPoints*`, `sf`. It would be nice, if the user could define a CRS at this point, in case it is not already present. If the starting object has further columns, these should be propagated through. I would like ordering by time stamp to be optional, because the user may have coordinates from several animals (but that might be a point of discussion).

**Output:**
An `sftraj` object.

**Additional information:**
In the `amt` package there is currently a function `amt::make_track` that does something similar for `data.frames` and `tibbles`. I would very much like to outsource this.

**Comment by jedalong** [comment]
I just saw a tweet about the new sfheaders package that might be relevant here as well.

**Comment by basille** [comment]
You are totally right. The idea is to have a generic `sftraj` function that handles all cases (i.e. probably a generic with many methods). We will start with the internal function though, but it is planned to be as broad as possible — at some point we'll ask for contributions for this, as we may not be able to cover all existing classes as input. At some point, we will start listing (and ask for people to contribute) all cases to be converted to `sftraj`.

@jedalong, thanks for pointing at `sfheaders`. I wasn't aware of this package. However, I am not sure I understand the benefits of using it. Lighter dependency?

**Comment by birderboone** [comment]
I'm re-opening some of these use-cases so theyre easier to find as people submit new ones.

**Comment by SymbolixAU** [comment]
> thanks for pointing at sfheaders. I wasn't aware of this package. However, I am not sure I understand the benefits of using it. Lighter dependency?

I'm the author of [`sfheaders`](https://github.com/dcooley/sfheaders) (also post as @dcooley). The design philosophy (and where I see the benefit) is you can [**link**](https://dcooley.github.io/sfheaders/articles/Cpp.html#linking-to-a-package) to the package, so all the code is callable at the C++ level (through `Rcpp`). 

If you're not using `Rcpp` you can still create most `sf` objects from R `data.frames` ([examples here](https://dcooley.github.io/sfheaders/articles/examples.html) )

And yes, no dependencies (apart from `Rcpp`)

Feel free to ping me with any questions :)

**Comment by basille** [comment]
Thanks Dave for following up. So it could potentially help to create `sf` objects much faster, by using lower-levels C++ functions — not something for users directly, but something that can be used in package functions, "under control". If I understand it correctly, I feel like it could well bring a very beneficial approach for large datasets…

**Comment by dcooley** [comment]
> not something for users directly, but something that can be used in package functions, "under control"

yes, exactly.

**Comment by dcooley** [comment]
I'm also working on a [gpx](https://github.com/dcooley/gpx) package which may overlap with `sftraj` too, so happy to collaborate where possible.

**Comment by basille** [comment]
Good to know! I don't know that there will be much overlap, given the focus of the two packages, but synergies can certainly be found! I see you use the M coordinate to store the time, this is something we've been considering for a while (see https://github.com/mablab/sftraj-proposal/issues/4).
