### ISSUE TITLE
[Use case] Transform projection of `sftraj`

### ISSUE THREAD

**Issue by jmsigner** [mablab/sftrack#5]
**Use case:**
Transform the coordinate reference system (CRS) of a `sftraj`.

**Requirements:**
A `sftraj`.

**Input:**
A `sftraj` with a valid CRS and a EPSG code.

**Output:**
A `sftraj` with the CRS transformed to the new ESPG code. 

**Additional information:**
I would expect this to be similar to `sf::st_transform`.

**Comment by basille** [comment]
Yes, indeed! Ideally, it *would be* `sf::st_transform`. `sftjraj` will rely heavily on `sf` objects (hence the name), so we will try to make it transparent for the user. In this use case, `sftraj` objects would need to nicely handle CRS and reprojections.

**Comment by birderboone** [comment]
I'm re-opening some of these use-cases so theyre easier to find as people submit new ones.
